name: Infosec Compliance

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  scan:
    name: Code scan
    uses: plume-design-inc/infosec-appsec/.github/workflows/compliance-scan.yml@main
    secrets:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
